In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

n=0

modelo = tf.keras.models.load_model('modelo.keras')

In [2]:
df = pd.read_csv('IRIS.csv')

base = df.drop(columns=['species'])

In [3]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [5]:
y_prev = modelo.predict(base)

5/5 [==============================] - 0s 5ms/step


In [4]:
scaler.fit(base)

base = scaler.transform(base)

In [6]:
print(y_prev)

[[9.97625053e-01 2.34420411e-03 3.08401468e-05]
 [9.90626335e-01 9.25128069e-03 1.22296260e-04]
 [9.96691823e-01 3.25701339e-03 5.11915096e-05]
 [9.94319797e-01 5.59159834e-03 8.85657646e-05]
 [9.98266518e-01 1.71201851e-03 2.15754390e-05]
 [9.97782648e-01 2.18391255e-03 3.33813259e-05]
 [9.97305036e-01 2.65090470e-03 4.41399861e-05]
 [9.96644914e-01 3.31357913e-03 4.14162678e-05]
 [9.91252005e-01 8.58253893e-03 1.65477119e-04]
 [9.93083477e-01 6.84652664e-03 6.99282609e-05]
 [9.97661948e-01 2.31143390e-03 2.66553470e-05]
 [9.96746421e-01 3.21251713e-03 4.10439025e-05]
 [9.92668331e-01 7.25123193e-03 8.04111187e-05]
 [9.96881247e-01 3.06769926e-03 5.10832106e-05]
 [9.98671174e-01 1.31640676e-03 1.23594027e-05]
 [9.99367774e-01 6.26785506e-04 5.51975609e-06]
 [9.98514950e-01 1.46127015e-03 2.38283719e-05]
 [9.97283936e-01 2.67141266e-03 4.46809936e-05]
 [9.95968699e-01 3.98486806e-03 4.64180157e-05]
 [9.98441994e-01 1.53654779e-03 2.13657131e-05]
 [9.92528081e-01 7.39859743e-03 7.337254

In [8]:
y_prev = [np.argmax(v) for v in y_prev]

In [9]:
print(y_prev)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
